name: seznam
description: "Seznam interview app."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_provider: ^2.1.0
  riverpod_annotation: ^2.3.5
  go_router: ^14.2.0
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  dio: ^5.4.3+1
  logger: ^2.3.0
  cached_network_image: ^3.3.1
  hive: ^2.2.3
  path_provider: ^2.1.3
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png